"""create aditya_associate_leads

Revision ID: 688840cecb19
Revises: 
Create Date: 2026-09-05 10:02:27.994269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688840cecb19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aditya_associate_leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aditya_associate_leads_created_at'), 'aditya_associate_leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_aditya_associate_leads_phone'), 'aditya_associate_leads', ['phone'], unique=False)
    op.create_index(op.f('ix_aditya_associate_leads_service'), 'aditya_associate_leads', ['service'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aditya_associate_leads_service'), table_name='aditya_associate_leads')
    op.drop_index(op.f('ix_aditya_associate_leads_phone'), table_name='aditya_associate_leads')
    op.drop_index(op.f('ix_aditya_associate_leads_created_at'), table_name='aditya_associate_leads')
    op.drop_table('aditya_associate_leads')
    # ### end Alembic commands ###
